### PR TITLE
Update express server to handle other content types

### PR DESCRIPTION
**Pull request by norbertdalecker**
Add more bodyparser to handle text/plain and www-formdata requests too.

### CODE REVIEW

**Comment by norbertdalecker** [comment]
@jormaechea any feedback about the changes?

**Comment by spacedaniel22** [comment]
+1

**Comment by jormaechea** [comment]
@norbertdalecker sorry for the delay. Let me take a look at this.

**Comment by jormaechea** [comment]
Looks good to me. Will release this soon.

**Comment by norbertdalecker** [comment]
Oh thank you very much! :)

**Comment by jormaechea** [comment]
Released in versión 1.5.1!  :rocket:

**Comment by norbertdalecker** [comment]
> Released in versión 1.5.1!

Thank you!

**Pull request merged**
