### PR TITLE
fix(Validation): Schema validator now accepts OpenAPI formats

### LINKED ISSUE #19: unknown format \"X\" is used in schema at path
I am receiving the following error when trying to make a call to the mock API using a request body that contains any number format:
```yaml
type: object
properties:
  branchId:
    type: number
    format: double # Any value here seems to cause an error
```

The error I am receiving is:
> "unknown format \"double\" is used in schema at path \"#/properties/branchId\""

I have attempted to tried various combinations of `type: number` and `type: integer` against each of the number formats defined [in the spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#data-types).
The spec also outlines that the `format` field is optional and can take any value.
It seems wrong that this error is then occurring due to a field that is considered optional.

In terms of fixing this, I see that there is a [line of code in the schema-valaidator](https://github.com/jormaechea/open-api-mocker/blob/bfce991538510af11b0db378945dd55197fc55f2/lib/schema-validator/index.js#L5) that adds the `password` format to the `unknownFormats` array used by _ajv_, is it a case of just adding in all the recognised formats to that array (`["int32", "int64", "float", "double", "byte", "binary", "date", "date-time", "password"]`)?
Whilst this would fix the problems for those schemas that use those default formats, any schema that uses (a completely valid) format that is not in that list will still throw this error. To prevent any further errors for formats, is it best to add some other kind of input to allow more unknown formats to be specified?

### PR DESCRIPTION
**Pull request by EdwardSalter**
Added ajv-openapi package to add support for the known formats that OpenAPI defines.
Unknown formats will no longer cause errors to be thrown and will instead write warnings to the console.

Fixes #19

### CODE REVIEW

**Review by jormaechea — CHANGES_REQUESTED** [review]
Please fix formatting issues. Run `npm run lint` to check them.

**Comment by EdwardSalter** [comment]
Whoops, I ran the tests before submitting the PR but forgot to run eslint.
I have ran eslint fix and pushed the changes.

Have you considered using something like husky or similar to run eslint/tests as git commit hook or having it run as a Github Workflow?

**Comment by jormaechea** [comment]
I have `husky` set up already, but accidentally upgraded to v5, which changed everything and also became paid.
I'm downgrading to v4 right now... 😞

**Review by jormaechea — APPROVED** [review]

**Comment by jormaechea** [comment]
Thanks for your contributions @EdwardSalter ! 🙌🏽

**Comment by EdwardSalter** [comment]
No problem, I have enjoyed working on this.
I have one more PR to come regarding adding support to connect to an existing express app rather than creating a new one which I am using to have this running as part of an Azure Function App using serverless-express.
It just needs some additional work to rebase it and tidy it up.

**Comment by jormaechea** [comment]
I suggest you raise an issue explaining a little bit this idea before the PR so we can reach an agreement on the implementation. It sounds like a big change (or maybe you solved it with some dependency injection or something, but just to be sure and you don't work in vain)

**Pull request merged**
