### PR TITLE
additional formats

### PR DESCRIPTION
**Pull request by ahoehn**
read additional formats if provided from commandliene path to solve https://github.com/jormaechea/open-api-mocker/issues/11

### CODE REVIEW

**Comment by jormaechea** [comment]
Hi @ahoehn, I'm not really comfortable about this solution.
I don't like the idea of needing a second file to validate an schema. I think this will be a headache for people using docker, having to handle a second volume and stuff.

I have two ideas in mind.
1. Add a --unknown-formats argument that delegates login to ajv's unknownFormats option ([docs](https://www.npmjs.com/package/ajv#options)) -- This would be the fastest.
2. Extend the OpenAPI specification with a `x-custom-formats` and define it there.


On the other hand, can you provide a minimum schema that fails due to validation?
Thanks!

**Comment by ahoehn** [comment]
hi @jormaechea 
You can test the problem with the official schema: https://petstore3.swagger.io/api/v3/openapi.yaml
If you try to add a pet by POST command, openapi-mocker will responde with "unknown format \"int64\" is used in schema at path \"#/properties/id\""
int64 is one of the official formats, but also custom formats are allowed.

About your ideas:
1. that would be possible, but with my solution you can also validate the format
2. depending on the fact that the input file is usally also used for documentation or generating clientcode, it doesn't make a lot of sense to extend it with custom configurations only known by open-api-mocker. That's why I've separated the formats from the oas3.yaml file. E.g. we use the OAS files for mocking, generating code and trought redocly for documentation.

Any other ideas to solve it?

**Comment by ahoehn** [comment]
How about this:
1. we add all the official formats to the server 
2. at startup the server scans the provided OAS3 spec and adds all the formats there to the ajv. Those string formats, where a pattern is provided, will be added as validated formats, the others without a patttern will be added to the ignored ones.

Like that we are very flexible and the spec file is the only needed param.
https://swagger.io/docs/specification/data-models/data-types/

**Comment by jormaechea** [comment]
@ahoehn 
1. Agreed. All standard formats should be added on startup (and validated if necesary). Any other `format` can be ignored, as any value should be valid (this is the ajv config `unknownFormats`)
2. I think that it's easier to run the `pattern` against the data on runtime (I mean, on each request). I don't see any benefit on scanning all the spec looking for patterns that you may not use. I suggest the following approach:
2.1. Upon first request arrives, if a `pattern` is found, we create a new RegExp and store it next to the pattern (ideally using a Symbol)
2.2. For that and subsequent requests, we validate using that RegExp

I think that's the best scenario, but I would accept it if the RegExp is generated on each request too. It won't be a preformance killer, and It can be improved later.

Btw, one PR for each feature (formats and patterns) would be great for simplicity.

What do you think?

**Comment by ahoehn** [comment]
I agree on that, will com up with 2 PRs

**Pull request closed without merging**
